# site settings
title: Matthias Bruns
subtitle: Android & Flutter Freelancer
email: info@matthiasbruns.com
description: Android & Fluttter Freelancer based in Rhede
baseurl: "" # the subpath of your site, e.g. /blog
url: '//matthiasbruns.com' # the base hostname & protocol for your site
author: Matthias Bruns
street_address: Blomenkamp 10a
city: Rhede
state: NRW
zip_code: 46414
country: Germany
phone: +49 171 8310017

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url: https://github.com/matthiasbruns
gitlab_url: https://gitlab.com/u/matthiasbruns
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/matthiasbruns/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/MTrax
xing_url: https://www.xing.com/profile/Matthias_Bruns13
aevz_url: https://app-entwickler-verzeichnis.de/programmierer/Bocholt/2721-

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
- jekyll-seo-tag
- jekyll-sitemap

emptyArray: [] 